### ISSUE TITLE
GraphEditor not found if docked

### ISSUE THREAD

**Issue by RedForty** [assumptionsoup/guppy_animation_tools#17]
If the modern graph editor is docked, this error pops up (2018.5):
Maya Exception:  window: Object 'graphEditor1Window' not found. - Branchless
Traceback (most recent call last):

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\slideAnimationKeysUI.py", line 757, in _onSliderPress
    _controller.beginSlide(value)

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\slideAnimationKeys.py", line 763, in beginSlide
    self.detectKeys()

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\slideAnimationKeys.py", line 694, in detectKeys
    segmentCollection = SegmentCollection.detect()

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\slideAnimationKeys.py", line 648, in detect
    curves = Curve.detectCurves(forceSelectedKeys=forceSelectedKeys)

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\slideAnimationKeys.py", line 290, in detectCurves
    graphEditor = selectedAttributes.GraphEditorInfo.detect(restrictToVisible=True)

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\selectedAttributes.py", line 169, in detect
    graphPanels = set(filter(cls._isPanelVisible, graphPanels))

  File "C:\Users\dklug\Documents\maya\scripts\guppy_animation_tools\scripts\selectedAttributes.py", line 142, in _isPanelVisible
    return (cmd.window(window, query=True, visible=True) and

RuntimeError: window: Object 'graphEditor1Window' not found.
![image](https://user-images.githubusercontent.com/3647153/94185061-af9bf700-fe59-11ea-9559-de58f0dc3507.png)

**Comment by assumptionsoup** [comment]
Just wanted to let you know I'm finally looking into this. It's easy enough to make the error go away, but it seems like it's harder to solve the problem and keep all of the original functionality. At least at first glance, Maya doesn't seem to be correctly reporting if the graphing tab is visible or not, unlike the normal window.

**Comment by roob0t** [comment]
Firstly thanks for these interesting tools! 
keen to try them out but was this ever fixed?.. Im getting a similar error (maya2020.4):

`guppy_animation_tools\scripts\selectedAttributes.py line 142: window: Object 'graphEditor1Window' not found. # `

Trying to use the Slide Animation Keys as Hotkeys but it won't work due my GE being Docked - Also the UI window pops behind Maya's Main window when using , but would be happy just getting the Hkey commands to work :) - tks!
